feat: Выполнить 2 этап диплома. v00
Andreyspb82/java-explore-with-me pull request #4
Opened 2023-10-25 22:02 UTC by Andreyspb82

2023-10-26 18:18 UTC, kalitva requested changes

2023-10-26 18:18 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        if (updateCompilation.getEvents() != null) {
То же самое, инвертируй условие и избавься от else

2023-10-26 18:18 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/user/service/UserServiceImpl.java
> +        } else {
else не нужен

2023-10-26 21:42 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +@Valid
Я решил, что без  аннотации `@Valid` не будет работать валидация на минимальные значения
 `@Min(0) @RequestParam(defaultValue = "0") int from`. 
Проверил работу своим запросом,  с отрицательным значением`from`,  без `@Valid`   отработало как надо.
Удалил из контроллеров `@Valid`

2023-10-26 21:42 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +    public Category() {
Исправил

2023-10-26 21:42 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/compilation/mapper/CompilationMapper.java
> +        }
Спасибо! Поправил.  Не обращая внимания на `return`, делал условия `if - else`, буду внимательнее.

2023-10-26 21:42 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        }
Спасибо! Поправил.

2023-10-26 21:42 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        if (updateCompilation.getEvents() != null) {
Переделал.

2023-10-26 21:43 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/event/controller/EventControllerAdmin.java
> +    private static final String FORMAT_TO_DATE = ("yyyy-MM-dd HH:mm:ss");
Перенес.

2023-10-26 21:43 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/request/model/ParticipationRequest.java
> +        if (this == o) return true;
Исправил.

2023-10-26 21:43 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/user/service/UserServiceImpl.java
> +
Удалил

2023-10-26 21:43 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/user/service/UserServiceImpl.java
> +        } else {
Спасибо! Удалил.

2023-10-26 21:43 UTC, Andreyspb82 commented on stats/stats-client/src/main/java/ru/practicum/ewm/client/stats/StatsClient.java
> +            throw new RuntimeException(e.getMessage());
Исправил.

2023-10-27 18:21 UTC, kalitva approved these changes

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    @ResponseStatus(HttpStatus.OK)
Статус OK по дефолту возвращается, можно не указывать явно

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +    public static Event mapToEventNew(NewEventDto newEvent, Category categoryById, User user) {
`categoryById --> category`
`mapToEventNew --> mapToNewEvent`

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +    public static Event mapToEventUpdate(Event event, UpdateEventUserRequest updateEvent) {
`updateEvent --> userRequest` Переменные не должны называться глагольным словосочетанием

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    public ApiError handleNotFoundException(final NotFoundException e) throws IOException {
Не надо декларировать `throws` в этих обработчиках

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +        e.printStackTrace(pw);
Стэктрейс ни в коем случае не надо вываливать наружу, это делает приложение уязвимым. Вообще, давай обойдемся без этих врайтеров, просто вернем из обработчика дто с ошибкой

2023-10-27 18:21 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/user/repository/UserRepository.java
> +    @Query(value = "select * from users u where u.id in ?1", nativeQuery = true)
Давай использовать `hql` вместо `sql`

2023-10-27 18:21 UTC, kalitva commented on stats/stats-dto/pom.xml
> +<!--        </dependency>-->
Удали закомментированный код

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    @ResponseStatus(HttpStatus.OK)
Удалил в контроллерах статус ОК

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +    public static Event mapToEventNew(NewEventDto newEvent, Category categoryById, User user) {
Исправил

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +    public static Event mapToEventUpdate(Event event, UpdateEventUserRequest updateEvent) {
Исправил

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    public ApiError handleNotFoundException(final NotFoundException e) throws IOException {
Исправил

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +        e.printStackTrace(pw);
Возвращать список стектрейсов было в описании к полю errors класса ApiError.
Вместо этого сделал e.getMessage().

2023-10-27 21:21 UTC, Andreyspb82 commented on main-service/src/main/java/ru/practicum/ewm/user/repository/UserRepository.java
> +    @Query(value = "select * from users u where u.id in ?1", nativeQuery = true)
Переделал, кроме 2 запросов.
Спасибо, `hql` лаконичнее

2023-10-27 21:21 UTC, Andreyspb82 commented on stats/stats-dto/pom.xml
> +<!--        </dependency>-->
Удалил

2023-10-27 21:25 UTC, merged